image: ubuntu:20.04

stages:
  - build
  - test
  - deploy

build:
  stage: build
  dependencies: [ ]
  cache: { }
  tags:
    - docker
  script:
    - echo "build stage"

test:
  stage: test
  dependencies: [ ]
  cache: { }
  tags:
    - docker
  script:
    - echo "test stage"


deploy:
  stage: deploy
  dependencies: [ ]
  cache: { }
  tags:
    - docker
  script:
    - echo "deploy stage"